version: '3'

services:
  db:
    image: postgres:15.2-alpine3.17
    environment:
      POSTGRES_USER: ${POSTGRES_USER} 
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

  app:
    image: registry.digitalocean.com/inultycom/inultycom:latest
    hostname: inultyapp
    volumes:
      - /usr/share/nginx/html/:/app/static_files
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env.prod

volumes:
  static_files:
