version: '3'

services:
  db:
    image: postgres:15.2-alpine3.17
    environment:
      POSTGRES_USER: ${PGUSER} 
      POSTGRES_PASSWORD: ${PGPASS}
      POSTGRES_DB: ${PGDB}
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

  nginx:
    image: nginx:1.23.4-alpine
    volumes:
      - ./nginx_conf/inultycom-nginx.conf:/etc/nginx/nginx.conf
      - ./static_files:/usr/share/nginx/html/
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - app

  app:
    image: repository.digitalocean.com/inultycom/inultycom:latest
    # image: inultycom:latest
    volumes:
      - ./static_files:/app/static_files
      - ./nginx_conf:/app/nginx_conf
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env.prod
    # environment:
      # DATABASE_URL: postgres://${PGUSER}:${PGPASS}@db:5432/${PGDB} # db is the db compose service
    #   DJANGO_SETTINGS_MODULE: inultycom.environments.staging #dev #prod
    # DATABASE_URL: postgres://iain:supersecret@db:5432/${PGDB} # db is the db compose service
    #   ALLOWED_HOSTS: ${ALLOWED_HOSTS}
    #   SECRET_KEY: ${SECRET_KEY}

volumes:
  static_files:
  nginx_conf:
