# Generated by Django 4.1.7 on 2023-04-05 00:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BlogArticle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("sub_title", models.CharField(max_length=200)),
                ("body", models.TextField()),
                ("hero_image", models.CharField(max_length=400, null=True)),
                ("slug", models.SlugField()),
                ("featured", models.BooleanField(null=True)),
                (
                    "published_at",
                    models.DateTimeField(null=True, verbose_name="date published"),
                ),
                ("likes", models.IntegerField(verbose_name="likes")),
                (
                    "created_at",
                    models.DateTimeField(
                        default=datetime.datetime.now, verbose_name="created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        default=datetime.datetime.now, verbose_name="updated at"
                    ),
                ),
            ],
        ),
    ]
